
---
spring:
  jpa:
    generate-ddl: true
    #database: MYSQL
    #properties:
     # hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: SpringMusic
 
# turn off the security on the actuator end points as this is a demo app
management:
  security:
    enabled: false