
---
spring:
  jpa:
    generate-ddl: true
    #database: MYSQL
    #properties:
     # hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: SpringMusic

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY}

# turn off the security on the actuator end points as this is a demo app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: sqlserver
  datasource:
    url: "jdbc:sqlserver://springsrv.database.windows.net:1433;database=springdemo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
