
---
spring:
  jpa:
    generate-ddl: true
    database: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: SpringMusic
  datasource:
    #type: org.apache.commons.dbcp2.BasicDataSource
    username: guest
    password: guest
    url: jdbc:mysql://localhost:3306/springmusic?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springmusic?useSSL=false
      username: guest
      password: guest
# turn off the security on the actuator end points as this is a demo app
management:
  security:
    enabled: false